### ISSUE TITLE
Basic bug, missunderstanding of URIs seems to be the cause

### ISSUE THREAD

**Issue by RasmusFey** [TudbuT/tuddyplus#4]
All links lead to /SOMETHING for example a link in index.html leads to "/login"
This would lead to a directory called "login", and would open the index.* in that directory, you need to set it to "/login.html" or setup a few folders

**Comment by TudbuT** [comment]
I know! But all files are not served normally. If you start the server, youll see it works.

**Comment by TudbuT** [comment]
lul xD
